sudo: required
services:
    - docker

before_install:
    - docker build -t farrukh806/docker-react-app -f Dockerfile.dev .


script:
    - docker run farrukh806/docker-react-app npm run test -- --coverage
